### ISSUE TITLE
Use HTML5-Charts

### ISSUE THREAD

**Issue by bioschaf** [jlolling/talendcomp_tJasperReportExec#13]
Hi Jan,

I am trying to use your component with a report that contains a HTML5-Chart. Report works fine in the Studio.

I figured out I need to load some libaries
- jasperreports-highcharts
- spring-core, spring-beans
- javax-servlet, rhino (for javascript)
- jasperreports-pro, jasperreports-license, com.jp.protection (license related)

And the path to the license needs to be specified in the "Run"-settings as _-Dcom.jaspersoft.jasperreports.license.location=_

In the end, it does not work. Maybe I have the wrong kind of license, error states it is "expired" which it is not.

Did you have any success with this or any of the "Pro" jasper-components?

**Comment by jlolling** [comment]
Unfortunately I have no possibility to test it or to reproduce the issue because I do not have a professional server running.
