### ISSUE TITLE
Suspicious "WARNING" in Jasper-Component

### ISSUE THREAD

**Issue by Jens2205** [jlolling/talendcomp_tJasperReportExec#14]
Hi Jan,

It's not a major issue, but I'm a bit confused about this "warning" we're seeing when using the Jasper component.

Here's the warning we get:
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.jasperreports.engine.util.ClassUtils (file:[...]/repository/net/sf/jasperreports/jasperreports/6.20.0/jasperreports-6.20.0.jar) to constructor com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl()
WARNING: Please consider reporting this to the maintainers of net.sf.jasperreports.engine.util.ClassUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

Our system configuration is the following:
Talend DI Studio 8
Java 11
Component Version: 7.3

Do you know, if there is a good reason for this warning? Or should we simply ignore it. 

Thank in advance for your help!
Best regards
Jens

PS: We are planning to move to Java 17. Have you noticed any drawbacks or compatibility issues with the latest releases of your components?

**Comment by jlolling** [comment]
I cannot do much here. It is a dependency of the JasperLibrary.
This message does not mean something does not work, so please ignore it.
