### ISSUE TITLE
Parameter conversion from date to string does not take Formatting into account

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tJasperReportExec#2]
When converting a context variable of type "Date" to a string, using the "convert Type" feature, the resulting string is not formatted as given by the "Date Conversion Format" Property. Instead it is always formatted "ddd MMM dd HH:mm:ss ZZZ yyyy"

For example see attached screenshot
![jasper_exec_date2string_conversion_error](https://user-images.githubusercontent.com/19684192/46207313-37140580-c327-11e8-8bfb-278a98be8bb6.JPG)

This is very confusing and inconsistent to the expectation.

**Comment by jlolling** [comment]
Accepted as bug. I will solve this as soon as possible.

**Comment by jlolling** [comment]
Sorry my fault. This is NOT a bug!
The parameter to parse the dateAsString parameter has the purpose to support converting the given String into a Date to use it in the report.
In your report now you have a Date and the rendering of this Date in the report must be configured in the report in the pattern of the text field.

Parameter:
String -> (here the mentioned pattern will be used) -> Date -> Report -> Date -> rendering -> String

**Comment by jlolling** [comment]
Here an example of such a Date parameter rendering:
![render_a_date_parameter_in_report](https://user-images.githubusercontent.com/8038781/48294480-c06d3a80-e484-11e8-8a11-fd701b4280b5.png)

Please use the Pattern setting to define the rendering of the Date typed value (it does not matter where it comes from)

**Comment by jlolling** [comment]
The mentioned pattern will be used currently only to convert a String into a Date. I will use this pattern also to render the Date as String.

**Comment by jlolling** [comment]
I have solved the issue. Please checkout the release 4.1 of the component.
Best regards
Jan
