### ISSUE TITLE
tjasperreportexec font layout glitch

### ISSUE THREAD

**Issue by ghost** [jlolling/talendcomp_tJasperReportExec#3]
hi Jan Lolling, 
I have been using tjasperreportexec to produce pdf file based on the data extracted from various databases. Thanks for your effort! Lately, there are some glitch to the pdf created. I didn’t change any setup since forever but when I tried to execute the same job via Talend 7.1 and JasperReport 6.6 
version throughout, the font will change automatically and some are overlapping with each other, some is truncated, etc (see attachments). When I tried to preview within JasperReport, it is working fine. When execution is done via Talend using this component, it will change the font layout. Please assist. 
Sorry as I may post the same issue in Talend Exchange.
Thank you.
Below is the pdf output if executed via Talend:
<img width="544" alt="tjasperreport pdf font glitch" src="https://user-images.githubusercontent.com/61131551/74622423-b9e76b80-517b-11ea-9255-507e7ec7de2d.png">
<img width="557" alt="tjasperreportexec pdf fixed text overflow" src="https://user-images.githubusercontent.com/61131551/74622428-bd7af280-517b-11ea-840d-9010089e69e4.png">
<img width="557" alt="tjasperreportexec pdf footer glitch" src="https://user-images.githubusercontent.com/61131551/74622429-beac1f80-517b-11ea-90bc-637eeb5c799e.png">
<img width="557" alt="tjasperreportexec pdf glitch" src="https://user-images.githubusercontent.com/61131551/74622431-bf44b600-517b-11ea-999e-5c96b4cd0b15.png">
<img width="185" alt="tjasperreportexec pdf text overflow" src="https://user-images.githubusercontent.com/61131551/74622432-bfdd4c80-517b-11ea-8084-0d70ecd683ec.png">

Output in TIBCO Jaspersoft:
<img width="468" alt="output in Tibco JasperReport" src="https://user-images.githubusercontent.com/61131551/74622878-683fe080-517d-11ea-8f85-ed0b6b33263b.png">

**Comment by jlolling** [comment]
You have to keep in mind:
The component uses the JasperLibrary 6.11 currently. To get the same result in the JasperStudio you have to change the compatibility to this version.
In some environments (like Linux) the fonts are replaced by Open Source fonts and they sometimes looks differently.

**Comment by ghost** [comment]
Hi,
Ok noted with this. Thank you.
